jobs:

  build-uberjar:
    name: Build uberjar
    run_when: &DEFAULT_TRIGGERS
      any branch matches:
        type: branch
        include_match: ^.+$
    context:
      include: cider-ci/context-components/uberjar.yml

    name: "Linting"
    description: |
      Code checks: static checks and metrics: complexity, duplication, and format,
      also other consistency checks.
    priority: 3
    run_when: *DEFAULT_TRIGGERS
    context:
      task_defaults:
        include: [cider-ci/task-components/env.yml]
        contexts:
        include:
          - path: cider-ci/context-components/lint/git-lint.yml
            submodule: [datalayer]
          - path: cider-ci/context-components/lint/rspec-lint.yml
            submodule: [datalayer]

