- name: auth directory
  file:
    path: /var/www/madek-auth
    state: directory
    mode: 0755

- name: maintenance page HTML
  template:
    src: maintenance.html
    dest: /var/www/madek-auth/503.html
    mode: 0644

- name: maintenance page config
  template:
    src: maintenance.conf
    dest: /etc/apache2/madek/conf.d/madek_800_auth.conf
    mode: 0644

- name: reload reverse-proxy
  service:
    name: apache2
    state: reloaded
